### ISSUE TITLE
Error: no such file or directory when running `measure_run_time.sh`

### ISSUE THREAD

**Issue by wilbowma** [atgeller/Wasm-Prechk-Artifact#5]
```
# ./utilities/measure_run_time.sh
Evaluating correlation
Compiling with plain wasmtime
Running
Error: No such file or directory (os error 2)
Compiling with prechk wasmtime
Running
Error: No such file or directory (os error 2)
Compiling without any checks
Running
Error: No such file or directory (os error 2)
Traceback (most recent call last):
  File "/root/PolyBenchC-4.2.1/utilities/generate_csv_line_from_hyperfine.py", line 5, in <module>
    from scipy import stats
ModuleNotFoundError: No module named 'scipy'
Evaluating covariance
Compiling with plain wasmtime
Running
Error: No such file or directory (os error 2)
Compiling with prechk wasmtime
Running
Error: No such file or directory (os error 2)
Compiling without any checks
Running
Error: No such file or directory (os error 2)
Traceback (most recent call last):
  File "/root/PolyBenchC-4.2.1/utilities/generate_csv_line_from_hyperfine.py", line 5, in <module>
    from scipy import stats
ModuleNotFoundError: No module named 'scipy'
Evaluating 2mm
Compiling with plain wasmtime
Running
Error: No such file or directory (os error 2)
Compiling with prechk wasmtime
...
```

Not sure if this is expected or not

**Comment by atgeller** [comment]
Ah, the scripts may require certain folders to be present, which I thought I had fixed but perhaps missed in a script. If so I'll add a command to create that folder at start-up.
