### ISSUE TITLE
json Decoder issue

### ISSUE THREAD

**Issue by wilbowma** [atgeller/Wasm-Prechk-Artifact#7]
when running measure_run_time
```
Evaluating deriche
Compiling with plain wasmtime
Running
Error: Command terminated with non-zero exit code: 1. Use the '-i'/'--ignore-failure' option if you want to ignore this. Alternatively, use the '--show-output' option to debug what went wrong.
Compiling with prechk wasmtime
Running
Error: Command terminated with non-zero exit code: 1. Use the '-i'/'--ignore-failure' option if you want to ignore this. Alternatively, use the '--show-output' option to debug what went wrong.
Compiling without any checks
Running
Error: Command terminated with non-zero exit code: 1. Use the '-i'/'--ignore-failure' option if you want to ignore this. Alternatively, use the '--show-output' option to debug what went wrong.
Traceback (most recent call last):
  File "/root/PolyBenchC-4.2.1/utilities/generate_csv_line_from_hyperfine.py", line 28, in <module>
    data = json.load(f)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Evaluating floyd-warshall
```

**Comment by atgeller** [comment]
Hmm, they're omitted from the evaluation times, but included in the verification and compilation times table in the paper, which is concerning. It looks like this happened for all three of the benchmarks in the medley folder. I'll check out why this is.

**Comment by atgeller** [comment]
I see, all three of them don't seem to have enough memory allocated statically, so they verify fine but don't run, and for some reason the script keeps running despite the errors.

**Comment by atgeller** [comment]
Alright I've changed the sizes and they run without error now.
