### ISSUE TITLE
Add instructions (and fix script) for generating graph

### ISSUE THREAD

**Issue by wilbowma** [atgeller/Wasm-Prechk-Artifact#9]
The user should be able to generate the graph from the paper, so they can easily compare how similar their measurements are. However:
```
> python make_graph.py 
Traceback (most recent call last):
  File "/root/PolyBenchC-4.2.1/utilities/make_graph.py", line 6, in <module>
    data = pd.read_csv('benchmark_data.csv')
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/usr/local/lib/python3.10/dist-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'benchmark_data.csv'
```

**Comment by atgeller** [comment]
Ah, I think that's an outdated script. I should add an instruction for doing that

**Comment by atgeller** [comment]
Yup, definitely need instructions as that is not intuitive.

**Comment by atgeller** [comment]
I added instructions for how to do that, but I'm wondering if the docker file should automatically run the experiments and scripts and simply mount the results once available?

**Comment by atgeller** [comment]
Sounds good. I'll close this with the added instructions then.
